[erebus] [ooo_cpu] Disable blocks that do not compile with `-std=c++20`
The compilation error is:

```
~/ChampSim/src/ooo_cpu.cc:530:40: error: no viable overloaded 'operator->'
if (prior != ROB.rend() && (prior->registers_instrs_depend_on_me.empty() || prior->registers_instrs_depend_on_me.back() != rob_it)) {
                                  ~~~~~^

/opt/homebrew/opt/llvm/include/c++/v1/__iterator/reverse_iterator.h:141:23: note: candidate function not viable: constraints not satisfied
constexpr pointer operator->() const
                      ^

/opt/homebrew/opt/llvm/include/c++/v1/__iterator/reverse_iterator.h:142:16: note:
because 'is_pointer_v<champsim::circular_buffer_iterator<champsim::circular_buffer<ooo_model_instr> > >' evaluated to false
      requires is_pointer_v<_Iter> || requires(const _Iter __i) { __i.operator->(); }
               ^

/opt/homebrew/opt/llvm/include/c++/v1/__iterator/reverse_iterator.h:142:67: note:
and '__i.operator->()' would be invalid:
'this' argument to member function 'operator->' has type 'const champsim::circular_buffer_iterator<champsim::circular_buffer<ooo_model_instr>>',
but function is not marked const

requires is_pointer_v<_Iter> || requires(const _Iter __i) { __i.operator->(); }

```